// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POSApp.API.Data;

namespace POSApp.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("POSApp.API.Models.Items", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("allow_alt_description");

                    b.Property<string>("category");

                    b.Property<float>("cost_price");

                    b.Property<int>("deleted");

                    b.Property<string>("description");

                    b.Property<DateTime>("end_date");

                    b.Property<int>("image_id");

                    b.Property<int>("is_serialized");

                    b.Property<int>("is_service");

                    b.Property<int>("item_id");

                    b.Property<string>("item_number");

                    b.Property<string>("name");

                    b.Property<int>("override_default_tax");

                    b.Property<string>("product_id");

                    b.Property<float>("promo_price");

                    b.Property<decimal>("reorder_level");

                    b.Property<DateTime>("start_date");

                    b.Property<int>("supplier_id");

                    b.Property<int>("tax_included");

                    b.Property<float>("unit_price");

                    b.HasKey("id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("POSApp.API.Models.user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("passwordhash");

                    b.Property<byte[]>("psswordsalt");

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("POSApp.API.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
